-- Fase 5 PR1 (issue #16): seed do conteudo real ja existente em lib/data/*
-- (questionario da cliente, 2026-08-04/05) + placeholders explicitamente rotulados.
-- Gerado a partir de lib/data/services.ts, team.ts, siteSettings.ts, testimonials.ts, blogPosts.ts.

insert into services (slug, title, description, long_description, category, image_url, "order", published) values
  ('reabilitacao-oral', 'Reabilitação Oral', 'Tratamento que combina as áreas necessárias para recuperar função e estética da boca.', 'A reabilitação oral reúne várias áreas da odontologia — prótese, implantes, dentística, periodontia — para reconstruir a boca de quem perdeu dentes ou teve a mastigação comprometida. O tratamento parte de um diagnóstico que olha dentes, gengiva, mordida e articulação em conjunto, e não um dente isolado. A partir dele, o plano é executado em etapas, na ordem que cada caso pede. O objetivo é devolver função e estética ao mesmo tempo.', null, null, 1, true),
  ('clinico-geral', 'Clínico Geral', 'Consultas de rotina, diagnóstico e prevenção para manter a saúde bucal em dia.', 'A odontologia clínica geral é a porta de entrada do cuidado com a boca: consulta de rotina, exame clínico, limpeza profissional e diagnóstico precoce de cárie, problema de gengiva e desgaste. É nessa avaliação que se define o que pode ser resolvido ali mesmo e o que precisa de uma especialidade. O acompanhamento periódico existe justamente para encontrar alterações enquanto ainda são simples de tratar.', null, null, 2, true),
  ('dentistica', 'Dentística', 'Restaurações e tratamentos estéticos para recuperar a forma e a função dos dentes.', 'A dentística é a especialidade que restaura dentes danificados por cárie, fratura ou desgaste, devolvendo forma, cor e função. Trabalha com materiais como resina composta e cerâmica, em restaurações diretas (feitas na própria consulta) ou indiretas (confeccionadas fora da boca e depois cimentadas). Também cuida de ajustes estéticos como fechamento de pequenos espaços e correção de manchas.', null, null, 3, true),
  ('implantodontia', 'Implantodontia', 'Reposição de dentes ausentes com implantes, devolvendo função e estética.', 'A implantodontia repõe dentes perdidos por meio de implantes: pinos de titânio instalados no osso da maxila ou da mandíbula, que passam a funcionar como a raiz de um dente novo. Sobre o implante se coloca uma coroa, uma ponte ou uma prótese maior, conforme o caso. Por se apoiar no osso, e não nos dentes vizinhos, é uma alternativa que preserva a estrutura ao redor. O planejamento envolve exames de imagem para avaliar volume ósseo e estruturas próximas.', null, null, 4, true),
  ('ortodontia', 'Ortodontia', 'Alinhamento dos dentes com aparelho, para uma mordida mais saudável e um sorriso mais harmônico.', 'A ortodontia corrige a posição dos dentes e o encaixe da mordida, usando aparelhos fixos, aparelhos móveis ou alinhadores transparentes. Além da estética do sorriso, um alinhamento adequado facilita a higienização e distribui melhor a força da mastigação, reduzindo desgaste desigual. O tratamento é acompanhado por consultas periódicas de ajuste até chegar ao resultado planejado.', null, null, 5, true),
  ('endodontia', 'Endodontia', 'Tratamento de canal para salvar dentes com a polpa comprometida.', 'A endodontia trata o interior do dente — a polpa, onde ficam nervos e vasos — quando ela é atingida por cárie profunda, trauma ou infecção. O tratamento de canal remove o tecido comprometido, desinfeta e preenche os condutos, o que permite manter o dente natural em vez de extraí-lo. Costuma ser indicado diante de dor intensa, sensibilidade persistente ao calor ou sinais de abscesso.', null, null, 6, true),
  ('harmonizacao-facial', 'Harmonização Facial', 'Procedimentos estéticos faciais que complementam o sorriso.', 'A harmonização orofacial reúne procedimentos estéticos da face que acompanham o resultado do tratamento odontológico, já que sorriso, lábios e contorno do rosto são lidos em conjunto. A proposta é equilibrar proporções respeitando as características de cada pessoa, e não padronizar o rosto. É uma área que cirurgiões-dentistas exercem dentro dos limites definidos pelo conselho da categoria, sempre após avaliação individual.', null, null, 7, true),
  ('cirurgias', 'Cirurgias', 'Procedimentos cirúrgicos odontológicos, da extração a casos mais complexos.', 'A cirurgia odontológica cobre os procedimentos que envolvem tecido ósseo ou gengival: extrações, remoção de lesões, ajustes de gengiva e preparo do osso para receber implantes. A maior parte é feita em consultório, com anestesia local e orientações específicas de cuidado no pós-operatório. O planejamento costuma incluir exames de imagem para avaliar raízes, nervos e estrutura óssea antes de qualquer intervenção.', null, null, 8, true),
  ('clareamento-dental', 'Clareamento Dental', 'Clareamento profissional para deixar o sorriso mais claro com segurança.', 'O clareamento dental usa géis à base de peróxido para reduzir a pigmentação do esmalte e da dentina, que escurecem com o tempo por causa de alimentos, bebidas e hábitos como o fumo. Pode ser feito em consultório, com moldeiras de uso domiciliar supervisionado, ou combinando os dois formatos. A avaliação prévia é o que define se existe cárie, restauração antiga ou sensibilidade que precise ser resolvida antes de começar.', null, null, 9, true),
  ('protese', 'Prótese', 'Próteses dentárias para repor dentes perdidos e recuperar a mastigação.', 'A prótese dentária repõe dentes perdidos com peças fixas ou removíveis — coroas, pontes, próteses parciais e totais — apoiadas nos dentes remanescentes ou em implantes. Repor o que falta não é só estética: ajuda a manter a mastigação, a fala e a posição dos dentes vizinhos, que tendem a se inclinar para o espaço vazio. Cada peça é planejada a partir de moldagem ou escaneamento da boca e ajustada na instalação.', null, null, 10, true),
  ('odontopediatria', 'Odontopediatria', 'Atendimento odontológico voltado para crianças, em ambiente acolhedor.', 'A odontopediatria cuida da saúde bucal de bebês, crianças e adolescentes, acompanhando o nascimento e a troca dos dentes. Envolve prevenção (orientação de higiene, aplicação de flúor, selantes), tratamento de cárie na dentição de leite e atenção a hábitos como uso prolongado de chupeta e respiração pela boca. Uma parte importante do trabalho é adaptar a criança ao consultório, para que a consulta não se torne fonte de medo.', null, null, 11, true),
  ('facetas', 'Facetas', 'Facetas para ajustar forma, cor e alinhamento do sorriso.', 'As facetas são lâminas finas de resina ou de porcelana fixadas na face externa dos dentes para corrigir cor, formato, pequenos desalinhamentos e espaços entre eles. O preparo varia conforme o material e o caso, podendo exigir desgaste mínimo do esmalte ou nenhum. É um procedimento estético que costuma ser planejado antes com prévia visual ou enceramento, para que o resultado seja discutido antes de começar.', null, null, 12, true),
  ('coroas', 'Coroas', 'Coroas dentárias para proteger e restaurar dentes desgastados ou tratados.', 'A coroa é uma peça que recobre todo o dente, indicada quando a estrutura que sobrou é insuficiente para uma restauração comum — por fratura, desgaste grande ou depois de um tratamento de canal. Pode ser feita em cerâmica, zircônia ou metalocerâmica, cimentada sobre o dente preparado ou sobre um implante. Protege o que restou do dente e devolve o formato original para a mastigação.', null, null, 13, true),
  ('extracao-de-sisos', 'Extração de Sisos', 'Remoção de dentes sisos, incluindo casos que precisam de acompanhamento cirúrgico.', 'Os sisos são os terceiros molares, que costumam nascer no fim da adolescência ou no início da vida adulta. Quando não há espaço suficiente na arcada, podem ficar inclusos ou irromper pela metade, o que favorece dor, inflamação da gengiva e cárie no dente vizinho. A indicação de remover é avaliada caso a caso, com radiografia para verificar posição, raízes e proximidade de estruturas como o nervo.', null, null, 14, true),
  ('atendimento-necessidades-especiais', 'Atendimento a Pacientes com Necessidades Especiais', 'Atendimento odontológico adaptado para pacientes com necessidades especiais.', 'A odontologia para pacientes com necessidades especiais atende pessoas cuja condição exige adaptação do atendimento: deficiências físicas ou intelectuais, transtornos do neurodesenvolvimento, doenças sistêmicas e limitações de mobilidade, entre outras. A adaptação pode envolver consultas mais curtas, ambiente com menos estímulos, mais tempo de acolhimento e comunicação próxima com quem acompanha o paciente. O cuidado bucal é o mesmo — o que muda é o formato, ajustado a cada pessoa.', null, null, 15, true);

insert into team_members (name, role, cro_number, bio, photo_url, "order", published) values
  ('Dra. Ariane Vaz Storrer', 'Cirurgiã-Dentista', null, 'Biografia ainda não enviada pela clínica (placeholder) — texto real entra assim que a Dra. Ariane enviar.', null, 1, true);

insert into site_settings (key, value) values
  ('clinic_name', 'Dra. Ariane Vaz Storrer – Odontologia Clínica e Estética'),
  ('clinic_tagline', 'Te ajudo a sorrir com confiança'),
  ('address', 'Rua Pedro Druszcz, 195 — Araucária, PR'),
  ('phone', '(41) 3031-6454'),
  ('whatsapp', '(41) 99998-1033'),
  ('email', 'arianevstorrer@gmail.com'),
  ('opening_hours', '09h00 às 19h00'),
  ('instagram_url', 'https://instagram.com/arianevstorrer'),
  ('facebook_url', ''),
  ('maps_url', 'https://maps.app.goo.gl/gYf86VX6W6BLMug59'),
  ('maps_embed_url', 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5476.634405728805!2d-49.39740764909308!3d-25.58935385739973!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94dd03d097843589%3A0xe9bc058baf9783d8!2sConsult%C3%B3rio%20Odontol%C3%B3gico%20Ariane%20Vaz%20Storrer!5e1!3m2!1spt-BR!2sbr!4v1785946063105!5m2!1spt-BR!2sbr'),
  ('payment_methods', 'Dinheiro, Pix, Cartão (débito e crédito)'),
  ('insurance', 'SINTRACIMENTO');

insert into testimonials (patient_name, content, rating, photo_url, consent_confirmed, published) values
  ('Paciente Exemplo 1 (placeholder)', 'Depoimento de placeholder. Substituir por depoimento real apenas com consentimento por escrito do paciente.', 5, null, true, true),
  ('Paciente Exemplo 2 (placeholder)', 'Depoimento de placeholder. Substituir por depoimento real apenas com consentimento por escrito do paciente.', 5, null, true, true);

insert into blog_posts (slug, title, content, cover_image_url, author_id, status, published_at) values
  ('post-exemplo-1', 'Post Exemplo 1 (placeholder)', 'Conteudo de placeholder do Post Exemplo 1. Substituir por material real quando (e se) o blog for confirmado.', null, null, 'published', '2026-01-01T00:00:00.000Z'),
  ('post-exemplo-2', 'Post Exemplo 2 (placeholder)', 'Conteudo de placeholder do Post Exemplo 2. Substituir por material real quando (e se) o blog for confirmado.', null, null, 'draft', null);
